/* DON'T EDIT THIS FILE. This is generated by 'scripts/update-lib-index.js' */
"use strict"

module.exports = {
    configs: {
        recommended: require("./configs/recommended.json"),
    },
    rules: {
        "exports-style": require("./rules/exports-style"),
        "no-deprecated-api": require("./rules/no-deprecated-api"),
        "no-extraneous-import": require("./rules/no-extraneous-import"),
        "no-extraneous-require": require("./rules/no-extraneous-require"),
        "no-missing-import": require("./rules/no-missing-import"),
        "no-missing-require": require("./rules/no-missing-require"),
        "no-unpublished-bin": require("./rules/no-unpublished-bin"),
        "no-unpublished-import": require("./rules/no-unpublished-import"),
        "no-unpublished-require": require("./rules/no-unpublished-require"),
        "no-unsupported-features/ecma": require("./rules/no-unsupported-features/ecma"),
        "process-exit-as-throw": require("./rules/process-exit-as-throw"),
        shebang: require("./rules/shebang"),

        // Deprecated rules.
        "no-hide-core-modules": require("./rules/no-hide-core-modules"),
        "no-unsupported-features": require("./rules/no-unsupported-features"),
    },
}
