/* DON'T EDIT THIS FILE. This is generated by 'scripts/update-lib-index.js' */
"use strict"

module.exports = {
    configs: {
        recommended: require("./configs/recommended.json"),
    },
    rules: {
        "exports-style": require("./rules/exports-style"),
        "no-deprecated-api": require("./rules/no-deprecated-api"),
        "no-extraneous-import": require("./rules/no-extraneous-import"),
        "no-extraneous-require": require("./rules/no-extraneous-require"),
        "no-missing-import": require("./rules/no-missing-import"),
        "no-missing-require": require("./rules/no-missing-require"),
        "no-unpublished-bin": require("./rules/no-unpublished-bin"),
        "no-unpublished-import": require("./rules/no-unpublished-import"),
        "no-unpublished-require": require("./rules/no-unpublished-require"),
        "no-unsupported-features/assert": require("./rules/no-unsupported-features/assert"),
        "no-unsupported-features/async_hooks": require("./rules/no-unsupported-features/async_hooks"),
        "no-unsupported-features/buffer": require("./rules/no-unsupported-features/buffer"),
        "no-unsupported-features/child_process": require("./rules/no-unsupported-features/child_process"),
        "no-unsupported-features/console": require("./rules/no-unsupported-features/console"),
        "no-unsupported-features/crypto": require("./rules/no-unsupported-features/crypto"),
        "no-unsupported-features/dns": require("./rules/no-unsupported-features/dns"),
        "no-unsupported-features/ecma": require("./rules/no-unsupported-features/ecma"),
        "no-unsupported-features/fs": require("./rules/no-unsupported-features/fs"),
        "no-unsupported-features/http2": require("./rules/no-unsupported-features/http2"),
        "no-unsupported-features/inspector": require("./rules/no-unsupported-features/inspector"),
        "no-unsupported-features/module": require("./rules/no-unsupported-features/module"),
        "no-unsupported-features/os": require("./rules/no-unsupported-features/os"),
        "no-unsupported-features/path": require("./rules/no-unsupported-features/path"),
        "no-unsupported-features/perf_hooks": require("./rules/no-unsupported-features/perf_hooks"),
        "no-unsupported-features/process": require("./rules/no-unsupported-features/process"),
        "no-unsupported-features/stream": require("./rules/no-unsupported-features/stream"),
        "no-unsupported-features/trace_events": require("./rules/no-unsupported-features/trace_events"),
        "process-exit-as-throw": require("./rules/process-exit-as-throw"),
        shebang: require("./rules/shebang"),

        // Deprecated rules.
        "no-hide-core-modules": require("./rules/no-hide-core-modules"),
        "no-unsupported-features": require("./rules/no-unsupported-features"),
    },
}
