/* DON'T EDIT THIS FILE. This is generated by 'scripts/update-lib-index.js' */
"use strict"

module.exports = {
    configs: {
        "recommended-module": require("./configs/recommended-module.js"),
        "recommended-script": require("./configs/recommended-script.js"),
        get recommended() {
            return require("./configs/recommended.js")()
        },
    },
    rules: {
        "callback-return": require("./rules/callback-return.js"),
        "exports-style": require("./rules/exports-style.js"),
        "file-extension-in-import": require("./rules/file-extension-in-import.js"),
        "global-require": require("./rules/global-require.js"),
        "handle-callback-err": require("./rules/handle-callback-err.js"),
        "no-callback-literal": require("./rules/no-callback-literal.js"),
        "no-deprecated-api": require("./rules/no-deprecated-api.js"),
        "no-exports-assign": require("./rules/no-exports-assign.js"),
        "no-extraneous-import": require("./rules/no-extraneous-import.js"),
        "no-extraneous-require": require("./rules/no-extraneous-require.js"),
        "no-missing-import": require("./rules/no-missing-import.js"),
        "no-missing-require": require("./rules/no-missing-require.js"),
        "no-mixed-requires": require("./rules/no-mixed-requires.js"),
        "no-new-require": require("./rules/no-new-require.js"),
        "no-path-concat": require("./rules/no-path-concat.js"),
        "no-process-env": require("./rules/no-process-env.js"),
        "no-process-exit": require("./rules/no-process-exit.js"),
        "no-restricted-import": require("./rules/no-restricted-import.js"),
        "no-restricted-require": require("./rules/no-restricted-require.js"),
        "no-sync": require("./rules/no-sync.js"),
        "no-unpublished-bin": require("./rules/no-unpublished-bin.js"),
        "no-unpublished-import": require("./rules/no-unpublished-import.js"),
        "no-unpublished-require": require("./rules/no-unpublished-require.js"),
        "no-unsupported-features/es-builtins": require("./rules/no-unsupported-features/es-builtins.js"),
        "no-unsupported-features/es-syntax": require("./rules/no-unsupported-features/es-syntax.js"),
        "no-unsupported-features/node-builtins": require("./rules/no-unsupported-features/node-builtins.js"),
        "prefer-global/buffer": require("./rules/prefer-global/buffer.js"),
        "prefer-global/console": require("./rules/prefer-global/console.js"),
        "prefer-global/process": require("./rules/prefer-global/process.js"),
        "prefer-global/text-decoder": require("./rules/prefer-global/text-decoder.js"),
        "prefer-global/text-encoder": require("./rules/prefer-global/text-encoder.js"),
        "prefer-global/url-search-params": require("./rules/prefer-global/url-search-params.js"),
        "prefer-global/url": require("./rules/prefer-global/url.js"),
        "prefer-promises/dns": require("./rules/prefer-promises/dns.js"),
        "prefer-promises/fs": require("./rules/prefer-promises/fs.js"),
        "process-exit-as-throw": require("./rules/process-exit-as-throw.js"),
        shebang: require("./rules/shebang.js"),

        // Deprecated rules.
        "no-hide-core-modules": require("./rules/no-hide-core-modules.js"),
        "no-unsupported-features": require("./rules/no-unsupported-features.js"),
    },
}
