jobs:
  - job: lint
    displayName: Lint
    pool:
      vmImage: Ubuntu-16.04
    steps:
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
          versionSpec: 12.x

      - script: npm install
        displayName: Install Packages

      - script: npm run -s lint
        displayName: Lint
